# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type check
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Fix spelling mistakes
    - gocritic      # Opinionated linter
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security checker

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofmt:
    simplify: true
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: false
      - name: var-naming
        disabled: false
  
  gosec:
    excludes:
      - G104  # Allow unhandled errors in some cases
      - G304  # Allow file path from variable (needed for config)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # Exclude fake implementations
    - path: fake\.go
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
